version: "3.9"

services:
  backend:
    build:
      context: ./backend said
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: backend
  angular:
    build:
      context: ./backend said 
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "80:80"
    container_name: azerty
